name: Latest blog post workflow
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */12 * * *"  # Run every 12 hours
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set timestamp
        id: set_timestamp
        run: echo "TIMESTAMP=$(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV

      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "4"
          feed_list: "https://politepol.com/fd/ojjQW3Cg1aKJ.xml"
          commit_message: "Updated latest blog posts on ${{ env.TIMESTAMP }}"

